import { Pool } from "pg";
import { felineGrimaceAssessmentSchema, regulationEvidenceSchema, type ConsentGrant, type FelineGrimaceAssessment, type PetProfile, type RegulationEvidence } from "@virtuapet/contracts";
import type { PetRepository } from "./repository.js";

const petFromRow = (row: Record<string, unknown>): PetProfile => ({
  petId: String(row.pet_id), guardianId: String(row.guardian_id), name: String(row.name), species: row.species as PetProfile["species"],
  ...(row.birth_date ? { birthDate: String(row.birth_date).slice(0, 10) } : {}), ...(row.microchip_id ? { microchipId: String(row.microchip_id) } : {}),
  recordVersion: Number(row.record_version), createdAt: new Date(String(row.created_at)).toISOString(), updatedAt: new Date(String(row.updated_at)).toISOString()
});
const grantFromRow = (row: Record<string, unknown>): ConsentGrant => ({ grantId: String(row.grant_id), petId: String(row.pet_id), grantorUserId: String(row.grantor_user_id), granteeId: String(row.grantee_id), scopes: row.scopes as ConsentGrant["scopes"], purpose: String(row.purpose), startsAt: new Date(String(row.starts_at)).toISOString(), expiresAt: new Date(String(row.expires_at)).toISOString(), revokedAt: row.revoked_at ? new Date(String(row.revoked_at)).toISOString() : null });

export class PostgresPetRepository implements PetRepository {
  constructor(private readonly pool: Pool) {}
  static fromConnectionString(connectionString: string) { const config = process.env.VIRTUAPET_ENV === "production" ? { connectionString, max: 10, ssl: { rejectUnauthorized: true } } : { connectionString, max: 10 }; return new PostgresPetRepository(new Pool(config)); }
  async create(pet: PetProfile) { const result = await this.pool.query(`INSERT INTO pet_profiles (pet_id,guardian_id,name,species,birth_date,microchip_id,record_version,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`, [pet.petId, pet.guardianId, pet.name, pet.species, pet.birthDate ?? null, pet.microchipId ?? null, pet.recordVersion, pet.createdAt, pet.updatedAt]); return petFromRow(result.rows[0]); }
  async findById(petId: string) { const result = await this.pool.query("SELECT * FROM pet_profiles WHERE pet_id=$1", [petId]); return result.rows[0] ? petFromRow(result.rows[0]) : undefined; }
  async createGrant(grant: ConsentGrant) { const result = await this.pool.query(`INSERT INTO consent_grants (grant_id,pet_id,grantor_user_id,grantee_id,scopes,purpose,starts_at,expires_at,revoked_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`, [grant.grantId, grant.petId, grant.grantorUserId, grant.granteeId, JSON.stringify(grant.scopes), grant.purpose, grant.startsAt, grant.expiresAt, grant.revokedAt]); return grantFromRow(result.rows[0]); }
  async listGrants(petId: string) { const result = await this.pool.query("SELECT * FROM consent_grants WHERE pet_id=$1 ORDER BY starts_at DESC", [petId]); return result.rows.map(grantFromRow); }
  async revokeGrant(grantId: string, revokedAt: string) { const result = await this.pool.query("UPDATE consent_grants SET revoked_at=$2 WHERE grant_id=$1 AND revoked_at IS NULL RETURNING *", [grantId, revokedAt]); return result.rows[0] ? grantFromRow(result.rows[0]) : undefined; }
  async createGrimaceAssessment(item: FelineGrimaceAssessment) { await this.pool.query(`INSERT INTO feline_grimace_assessments (assessment_id,pet_id,assessor_user_id,clinic_id,assessed_at,assessor_training_confirmed,context,action_units,total_score,veterinary_review_required,recorded_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`, [item.assessmentId,item.petId,item.assessorUserId,item.clinicId,item.assessedAt,item.assessorTrainingConfirmed,item.context ?? null,JSON.stringify(item.actionUnits),item.totalScore,item.veterinaryReviewRequired,item.recordedAt]); return item; }
  async listGrimaceAssessments(petId: string): Promise<FelineGrimaceAssessment[]> { const result = await this.pool.query("SELECT * FROM feline_grimace_assessments WHERE pet_id=$1 ORDER BY assessed_at DESC", [petId]); return result.rows.map(row => felineGrimaceAssessmentSchema.parse({ assessmentId:String(row.assessment_id),petId:String(row.pet_id),assessorUserId:String(row.assessor_user_id),clinicId:String(row.clinic_id),assessedAt:new Date(row.assessed_at).toISOString(),assessorTrainingConfirmed:row.assessor_training_confirmed,...(row.context ? {context:String(row.context)} : {}),actionUnits:row.action_units,totalScore:Number(row.total_score),veterinaryReviewRequired:Boolean(row.veterinary_review_required),recordedAt:new Date(row.recorded_at).toISOString() })); }
  async createRegulationEvidence(item: RegulationEvidence) { await this.pool.query(`INSERT INTO regulation_evidence (evidence_id,country_code,region_code,authority,source_url,title,retrieved_at,effective_date,evidence_excerpt,status,reviewer_user_id,human_verified_at,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`, [item.evidenceId,item.countryCode,item.regionCode ?? null,item.authority,item.sourceUrl,item.title,item.retrievedAt,item.effectiveDate ?? null,item.evidenceExcerpt,item.status,item.reviewerUserId,item.humanVerifiedAt,item.createdAt]); return item; }
  async listRegulationEvidence(countryCode: string, regionCode?: string): Promise<RegulationEvidence[]> { const result = await this.pool.query("SELECT * FROM regulation_evidence WHERE country_code=$1 AND ($2::text IS NULL OR region_code=$2) ORDER BY retrieved_at DESC", [countryCode, regionCode ?? null]); return result.rows.map(row => regulationEvidenceSchema.parse({ evidenceId:String(row.evidence_id),countryCode:String(row.country_code).trim(),...(row.region_code ? {regionCode:String(row.region_code)} : {}),authority:String(row.authority),sourceUrl:String(row.source_url),title:String(row.title),retrievedAt:new Date(row.retrieved_at).toISOString(),...(row.effective_date ? {effectiveDate:String(row.effective_date).slice(0,10)} : {}),evidenceExcerpt:String(row.evidence_excerpt),status:row.status,reviewerUserId:String(row.reviewer_user_id),humanVerifiedAt:row.human_verified_at ? new Date(row.human_verified_at).toISOString() : null,createdAt:new Date(row.created_at).toISOString() })); }
  async clear() { throw new Error("clear is unavailable for persistent repositories"); }
  async close() { await this.pool.end(); }
}
