import { Pool } from "pg";
import { felineGrimaceAssessmentSchema, regulationEvidenceSchema, type Appointment, type ClinicMessage, type ConsentGrant, type FelineGrimaceAssessment, type InventoryItem, type Membership, type Organization, type PetProfile, type Recall, type RegulationEvidence } from "@virtuapet/contracts";
import type { PetRepository } from "./repository.js";

const petFromRow = (row: Record<string, unknown>): PetProfile => ({
  petId: String(row.pet_id), guardianId: String(row.guardian_id), name: String(row.name), species: row.species as PetProfile["species"],
  ...(row.birth_date ? { birthDate: String(row.birth_date).slice(0, 10) } : {}), ...(row.microchip_id ? { microchipId: String(row.microchip_id) } : {}),
  recordVersion: Number(row.record_version), createdAt: new Date(String(row.created_at)).toISOString(), updatedAt: new Date(String(row.updated_at)).toISOString()
});
const grantFromRow = (row: Record<string, unknown>): ConsentGrant => ({ grantId: String(row.grant_id), petId: String(row.pet_id), grantorUserId: String(row.grantor_user_id), granteeId: String(row.grantee_id), scopes: row.scopes as ConsentGrant["scopes"], purpose: String(row.purpose), startsAt: new Date(String(row.starts_at)).toISOString(), expiresAt: new Date(String(row.expires_at)).toISOString(), revokedAt: row.revoked_at ? new Date(String(row.revoked_at)).toISOString() : null });

export class PostgresPetRepository implements PetRepository {
  constructor(private readonly pool: Pool) {}
  static fromConnectionString(connectionString: string) { const config = process.env.VIRTUAPET_ENV === "production" ? { connectionString, max: 10, ssl: { rejectUnauthorized: true } } : { connectionString, max: 10 }; return new PostgresPetRepository(new Pool(config)); }
  async create(pet: PetProfile) { const result = await this.pool.query(`INSERT INTO pet_profiles (pet_id,guardian_id,name,species,birth_date,microchip_id,record_version,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`, [pet.petId, pet.guardianId, pet.name, pet.species, pet.birthDate ?? null, pet.microchipId ?? null, pet.recordVersion, pet.createdAt, pet.updatedAt]); return petFromRow(result.rows[0]); }
  async findById(petId: string) { const result = await this.pool.query("SELECT * FROM pet_profiles WHERE pet_id=$1", [petId]); return result.rows[0] ? petFromRow(result.rows[0]) : undefined; }
  async createGrant(grant: ConsentGrant) { const result = await this.pool.query(`INSERT INTO consent_grants (grant_id,pet_id,grantor_user_id,grantee_id,scopes,purpose,starts_at,expires_at,revoked_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`, [grant.grantId, grant.petId, grant.grantorUserId, grant.granteeId, JSON.stringify(grant.scopes), grant.purpose, grant.startsAt, grant.expiresAt, grant.revokedAt]); return grantFromRow(result.rows[0]); }
  async listGrants(petId: string) { const result = await this.pool.query("SELECT * FROM consent_grants WHERE pet_id=$1 ORDER BY starts_at DESC", [petId]); return result.rows.map(grantFromRow); }
  async revokeGrant(grantId: string, revokedAt: string) { const result = await this.pool.query("UPDATE consent_grants SET revoked_at=$2 WHERE grant_id=$1 AND revoked_at IS NULL RETURNING *", [grantId, revokedAt]); return result.rows[0] ? grantFromRow(result.rows[0]) : undefined; }
  async createGrimaceAssessment(item: FelineGrimaceAssessment) { await this.pool.query(`INSERT INTO feline_grimace_assessments (assessment_id,pet_id,assessor_user_id,clinic_id,assessed_at,assessor_training_confirmed,context,action_units,total_score,veterinary_review_required,recorded_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`, [item.assessmentId,item.petId,item.assessorUserId,item.clinicId,item.assessedAt,item.assessorTrainingConfirmed,item.context ?? null,JSON.stringify(item.actionUnits),item.totalScore,item.veterinaryReviewRequired,item.recordedAt]); return item; }
  async listGrimaceAssessments(petId: string): Promise<FelineGrimaceAssessment[]> { const result = await this.pool.query("SELECT * FROM feline_grimace_assessments WHERE pet_id=$1 ORDER BY assessed_at DESC", [petId]); return result.rows.map(row => felineGrimaceAssessmentSchema.parse({ assessmentId:String(row.assessment_id),petId:String(row.pet_id),assessorUserId:String(row.assessor_user_id),clinicId:String(row.clinic_id),assessedAt:new Date(row.assessed_at).toISOString(),assessorTrainingConfirmed:row.assessor_training_confirmed,...(row.context ? {context:String(row.context)} : {}),actionUnits:row.action_units,totalScore:Number(row.total_score),veterinaryReviewRequired:Boolean(row.veterinary_review_required),recordedAt:new Date(row.recorded_at).toISOString() })); }
  async createRegulationEvidence(item: RegulationEvidence) { await this.pool.query(`INSERT INTO regulation_evidence (evidence_id,country_code,region_code,authority,source_url,title,retrieved_at,effective_date,evidence_excerpt,status,reviewer_user_id,human_verified_at,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`, [item.evidenceId,item.countryCode,item.regionCode ?? null,item.authority,item.sourceUrl,item.title,item.retrievedAt,item.effectiveDate ?? null,item.evidenceExcerpt,item.status,item.reviewerUserId,item.humanVerifiedAt,item.createdAt]); return item; }
  async listRegulationEvidence(countryCode: string, regionCode?: string): Promise<RegulationEvidence[]> { const result = await this.pool.query("SELECT * FROM regulation_evidence WHERE country_code=$1 AND ($2::text IS NULL OR region_code=$2) ORDER BY retrieved_at DESC", [countryCode, regionCode ?? null]); return result.rows.map(row => regulationEvidenceSchema.parse({ evidenceId:String(row.evidence_id),countryCode:String(row.country_code).trim(),...(row.region_code ? {regionCode:String(row.region_code)} : {}),authority:String(row.authority),sourceUrl:String(row.source_url),title:String(row.title),retrievedAt:new Date(row.retrieved_at).toISOString(),...(row.effective_date ? {effectiveDate:String(row.effective_date).slice(0,10)} : {}),evidenceExcerpt:String(row.evidence_excerpt),status:row.status,reviewerUserId:String(row.reviewer_user_id),humanVerifiedAt:row.human_verified_at ? new Date(row.human_verified_at).toISOString() : null,createdAt:new Date(row.created_at).toISOString() })); }
  async verifyRegulationEvidence(evidenceId: string, verifiedAt: string) { const result = await this.pool.query("UPDATE regulation_evidence SET human_verified_at=$2 WHERE evidence_id=$1 RETURNING *",[evidenceId,verifiedAt]); const row=result.rows[0]; return row ? regulationEvidenceSchema.parse({evidenceId:String(row.evidence_id),countryCode:String(row.country_code).trim(),...(row.region_code?{regionCode:String(row.region_code)}:{}),authority:String(row.authority),sourceUrl:String(row.source_url),title:String(row.title),retrievedAt:new Date(row.retrieved_at).toISOString(),...(row.effective_date?{effectiveDate:String(row.effective_date).slice(0,10)}:{}),evidenceExcerpt:String(row.evidence_excerpt),status:row.status,reviewerUserId:String(row.reviewer_user_id),humanVerifiedAt:new Date(row.human_verified_at).toISOString(),createdAt:new Date(row.created_at).toISOString()}):undefined; }
  async createOrganization(item: Organization) { await this.pool.query("INSERT INTO organizations(organization_id,name,kind,created_at) VALUES($1,$2,$3,$4)",[item.organizationId,item.name,item.kind,item.createdAt]); return item; }
  async createMembership(item: Membership) { await this.pool.query("INSERT INTO organization_memberships(membership_id,organization_id,user_id,role,status,created_at,revoked_at) VALUES($1,$2,$3,$4,$5,$6,$7)",[item.membershipId,item.organizationId,item.userId,item.role,item.status,item.createdAt,item.revokedAt]); return item; }
  async findMembership(organizationId: string,userId: string): Promise<Membership|undefined> { const result=await this.pool.query("SELECT * FROM organization_memberships WHERE organization_id=$1 AND user_id=$2 AND status='active'",[organizationId,userId]); const row=result.rows[0]; return row?{membershipId:String(row.membership_id),organizationId:String(row.organization_id),userId:String(row.user_id),role:row.role,status:row.status,createdAt:new Date(row.created_at).toISOString(),revokedAt:row.revoked_at?new Date(row.revoked_at).toISOString():null}:undefined; }
  async createAppointment(item: Appointment) { await this.pool.query("INSERT INTO appointments(appointment_id,clinic_id,pet_id,starts_at,duration_minutes,reason,assigned_user_id,status,created_by_user_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[item.appointmentId,item.clinicId,item.petId,item.startsAt,item.durationMinutes,item.reason,item.assignedUserId??null,item.status,item.createdByUserId,item.createdAt]); return item; }
  async listAppointments(clinicId: string): Promise<Appointment[]> { const result=await this.pool.query("SELECT * FROM appointments WHERE clinic_id=$1 ORDER BY starts_at",[clinicId]); return result.rows.map(row=>({appointmentId:String(row.appointment_id),clinicId:String(row.clinic_id),petId:String(row.pet_id),startsAt:new Date(row.starts_at).toISOString(),durationMinutes:Number(row.duration_minutes),reason:String(row.reason),...(row.assigned_user_id?{assignedUserId:String(row.assigned_user_id)}:{}),status:row.status,createdByUserId:String(row.created_by_user_id),createdAt:new Date(row.created_at).toISOString()})); }
  async createRecall(item: Recall) { await this.pool.query("INSERT INTO recalls(recall_id,clinic_id,pet_id,due_at,reason,status,created_by_user_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[item.recallId,item.clinicId,item.petId,item.dueAt,item.reason,item.status,item.createdByUserId,item.createdAt]); return item; }
  async createInventoryItem(item: InventoryItem) { await this.pool.query("INSERT INTO inventory_items(inventory_item_id,clinic_id,sku,name,quantity_on_hand,reorder_point,updated_by_user_id,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[item.inventoryItemId,item.clinicId,item.sku,item.name,item.quantityOnHand,item.reorderPoint,item.updatedByUserId,item.updatedAt]); return item; }
  async createClinicMessage(item: ClinicMessage) { await this.pool.query("INSERT INTO clinic_messages(message_id,clinic_id,pet_id,subject,body,author_user_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)",[item.messageId,item.clinicId,item.petId,item.subject,item.body,item.authorUserId,item.createdAt]); return item; }
  async clear() { throw new Error("clear is unavailable for persistent repositories"); }
  async close() { await this.pool.end(); }
}
